### ISSUE TITLE
cups-2.0.1_2, x86-64, Directory "/usr/lib/cups/cgi-bin" has insecure permissions (040775/uid=0/gid=0).

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#835] opened 2015-01-10 13:25 UTC
All Directorys in /usr/lib/cups has Group write permissions, so cups can't configure printers.

**Comment by xtraeme** [comment] 2015-01-11 08:54
Just installed cups and I can see the dirs are 0755:

```
[juan@leysa void-packages]$ ls -l /usr/lib/cups/
total 24
drwxr-xr-x 2 root root 4096 ene 11 09:53 backend
drwxr-xr-x 2 root root 4096 ene 11 09:53 cgi-bin
drwxr-xr-x 2 root root 4096 ene 11 09:53 daemon
drwxr-xr-x 2 root root 4096 ene 11 09:53 filter
drwxr-xr-x 2 root root 4096 ene 11 09:53 monitor
drwxr-xr-x 2 root root 4096 ene 11 09:53 notifier
[juan@leysa void-packages]$
```

The current binary package also has proper permissions:

```
-rwxr-xr-x  0 0      0       59536 nov 29 23:47 ./usr/lib/cups/cgi-bin/admin.cgi
-rwxr-xr-x  0 0      0       14416 nov 29 23:47 ./usr/lib/cups/cgi-bin/classes.cgi
-rwxr-xr-x  0 0      0       14400 nov 29 23:47 ./usr/lib/cups/cgi-bin/help.cgi
-rwxr-xr-x  0 0      0       10304 nov 29 23:47 ./usr/lib/cups/cgi-bin/jobs.cgi
-rwxr-xr-x  0 0      0       14424 nov 29 23:47 ./usr/lib/cups/cgi-bin/printers.cgi
```

Are you sure it's not a local problem?

**Comment by pulux** [comment] 2015-01-11 09:04
Hm?
Yesterday I installed cups and run in that issue, what can goes localy wrong?.

**Comment by xtraeme** [comment] 2015-01-11 09:05
As you can see the permissions on my system and in the binary package are perfectly fine.

Unless you provide some way to reproduce it, I'll think it's a local issue.

**Comment by xtraeme** [comment] 2015-01-11 09:12
I think what happened here was that `/usr/lib/cups/cgi-bin` existed in your system and had 0775 permissions and then xbps preserved the existing permissions on that directory.

You should find out why your system had those directories with wrong permissions. I'm not able to reproduce it unless the directory already exists before the pkg installation.

**Comment by pulux** [comment] 2015-01-11 09:16
# ls -l /usr/lib/cup*
ls: Zugriff auf /usr/lib/cup* nicht möglich: Datei oder Verzeichnis nicht gefunden
# xbps-install cups                                                                                                                                                                                                            

Name            Action    Version           New version            Download size
libcups-filters install   -                 1.0.61_2               - 
poppler-utils   install   -                 0.28.1_1               - 
libqpdf         install   -                 5.1.2_1                - 
cups-filters    install   -                 1.0.61_2               - 
bc              install   -                 1.06.95_5              - 
cups            install   -                 2.0.1_2                - 

Size required on disk:          14MB
Free space on disk:             24GB

Do you want to continue? [YES/no] 

[*] Downloading binary packages

[*] Verifying package integrity
libcups-filters-1.0.61_2: verifying RSA signature...
poppler-utils-0.28.1_1: verifying RSA signature...
libqpdf-5.1.2_1: verifying RSA signature...
cups-filters-1.0.61_2: verifying RSA signature...
bc-1.06.95_5: verifying RSA signature...
cups-2.0.1_2: verifying RSA signature...

[*] Running transaction tasks
libcups-filters-1.0.61_2: unpacking ...
poppler-utils-0.28.1_1: unpacking ...
libqpdf-5.1.2_1: unpacking ...
cups-filters-1.0.61_2: unpacking ...
bc-1.06.95_5: unpacking ...
cups-2.0.1_2: unpacking ...

[*] Configuring unpacked packages
libcups-filters-1.0.61_2: configuring ...
libcups-filters-1.0.61_2: installed successfully.
poppler-utils-0.28.1_1: configuring ...
poppler-utils-0.28.1_1: installed successfully.
libqpdf-5.1.2_1: configuring ...
libqpdf-5.1.2_1: installed successfully.
cups-filters-1.0.61_2: configuring ...
cups-filters-1.0.61_2: installed successfully.
bc-1.06.95_5: configuring ...
bc-1.06.95_5: installed successfully.
cups-2.0.1_2: configuring ...
Updating GTK+ icon cache for /usr/share/icons/hicolor...
Updating MIME database...
cups-2.0.1_2: installed successfully.

0 downloaded, 6 installed, 0 updated, 6 configured, 0 removed.
# ls -l /usr/lib/cups*
insgesamt 24
drwxrwxr-x 2 root root 4096 11. Jan 10:15 backend
drwxrwxr-x 2 root root 4096 11. Jan 10:15 cgi-bin
drwxrwxr-x 2 root root 4096 11. Jan 10:15 daemon
drwxrwxr-x 2 root root 4096 11. Jan 10:15 filter
drwxrwxr-x 2 root root 4096 11. Jan 10:15 monitor
drwxrwxr-x 2 root root 4096 11. Jan 10:15 notifier

**Comment by xtraeme** [comment] 2015-01-11 09:18
Output of `umask` ?

**Comment by pulux** [comment] 2015-01-11 09:21
0002

**Comment by xtraeme** [comment] 2015-01-11 09:24
Are you installing with root directly or via sudo?

**Comment by pulux** [comment] 2015-01-11 09:25
as root

**Comment by xtraeme** [comment] 2015-01-11 09:26
Ok, I can reproduce it with root. Thanks.

**Comment by xtraeme** [comment] 2015-01-11 09:46
Got a fix for xbps... will be released in some minutes.

**Comment by xtraeme** [comment] 2015-01-11 10:04
Fixed with xbps-0.41.3_3, see 54357100cc489bdd73efe5c23b0d8a1398074fa2

**Comment by xtraeme** [comment] 2015-01-11 10:11
I verified it works correctly now.

**Comment by xtraeme** [comment] 2015-01-11 10:13
If you've installed many packages with root and your umask wasn't set to 022, you'll have to correct those directories to be 0755:

```
$ find /usr -type d -perm 0775
```

**Comment by xtraeme** [comment] 2015-01-11 10:55
I also updated `/etc/pam.d/su{,-l}` to set a proper umask(2) via pam_umask(8).

Fixed, thanks.

**Closed by xtraeme** 2015-01-11 10:55 UTC
