### ISSUE TITLE
Clang 3.9.0: Option 'asm-instrumentation' registered more than once

### ISSUE THREAD

**Issue by iamgreaser** [voidlinux/void-packages#4724] opened 2016-09-06 04:06 UTC
This occurs when compiling at least some things with LTO (`-flto` switch). IIRC this crops up when compiling CEN64 and the paraLLEl libretro core, both from Git.

Relevant bug, now in release: https://llvm.org/bugs/show_bug.cgi?id=27590

I have rolled back to Clang+LLVM 3.8.1 which does not have this bug.

This most likely shares the same root cause with #4722 .

**Comment by pullmoll** [comment] 2016-09-06 10:25
In theory the problem is fixed, but it looks like building the (bloated) llvm-3.9.0 in https://github.com/voidlinux/void-packages/commit/b7b6c837ae079d340fb02e6e59719e1f2f3e6e7d killed the build bots.

**Comment by chneukirchen** [comment] 2016-09-06 11:42
If that linked bug report is true, we could split off lld into a separate package (but I doubt it really works).

**Comment by chneukirchen** [comment] 2016-09-06 12:01
FWIW, disabling lld is not enough.

**Comment by chneukirchen** [comment] 2016-09-16 13:54
Tracked by #4722, closing.

**Closed by chneukirchen** 2016-09-16 13:54 UTC
