### ISSUE TITLE
musl builders date/time issue?

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5487] opened 2017-01-08 02:16 UTC
It looks like the *-musl builders rebuild packages which are already done.
Perhaps an issue with the machine's date/time setting (ntpd)?

**Comment by the-maldridge** [comment] 2017-01-09 00:15
I've re-synchronized the time on kc, but it wasn't that far out.

**Comment by pullmoll** [comment] 2017-01-09 06:20
It may be something else. For some reason it still rebuilds simgear + flightgear over and over again.

**Comment by pullmoll** [comment] 2017-01-11 07:12
Perhaps something is wrong with the user/group or access rights of the generated Makefile for the github updates. I don't see the pkgs being rebuilt over and over in the [`found packages`](https://build.voidlinux.eu/builders/x86_64-musl_builder/builds/33/steps/shell_2/logs/stdio)  but they still appear in the [`property 'pkgs'`](https://build.voidlinux.eu/builders/x86_64-musl_builder/builds/33/steps/setproperty/logs/stdio)

**Comment by pullmoll** [comment] 2017-01-11 15:32
Seems to be solved now?

**Comment by xtraeme** [comment] 2017-01-11 17:49
This has not been yet fixed.

**Comment by Duncaen** [comment] 2017-01-11 18:14
Fixed it now, the build ids were reset and old folders with `repo-checkvers.txt` files from previous build jobs existed, `xbps-bulk` just appended the new ones.
Deleted all job directories larger then 43.

**Comment by xtraeme** [comment] 2017-01-11 18:41
I guess the glibc builders, the arm ones also have this problem.

**Comment by xtraeme** [comment] 2017-01-11 18:42
Sorry, the arm musl builders are the ones exhibing this problem, not the glibc ones.

**Comment by Duncaen** [comment] 2017-01-11 18:45
Ah fixed now, forgot to clean the last few builds before 100, I cleaned aarch64 too.

**Comment by xtraeme** [comment] 2017-01-11 18:52
Please clean all of them. To be sure.

2017-01-11 19:45 GMT+01:00 Duncan Overbruck <notifications@github.com>:

**Comment by xtraeme** [comment] 2017-01-11 19:48
```
=> linux4.4-4.4.41_1: verifying checksum for distfile 'linux-4.4.41.tar.xz'... ln: failed to create hard link '/host/sources/by_sha256/8a6d847f5ffa3188d5c9d266ebaca5bb77c8af7637bd3bf74ab6747d5e7646fc_linux-4.4.41.tar.xz' => '/host/sources/linux4.4-4.4.41/linux-4.4.41.tar.xz': Permission denied```

**Comment by Duncaen** [comment] 2017-01-11 20:48
@the-maldridge can you check this? And delete all existing build job directories in `slave-*/*_builder` on the main server.

**Comment by the-maldridge** [comment] 2017-01-13 19:50
The root cause was determined to be a collision of build IDs when the buildmaster was recovered after an LVM crash earlier in the month.  I recommend closing this ticket.

**Comment by Duncaen** [comment] 2017-01-14 00:39
What about the permission error @xtraeme posted?

**Comment by pullmoll** [comment] 2017-02-23 13:41
@Duncaen perhaps this is related @chneukirchen 's findings in #5801 (builders use `chpst -u`).

**Comment by the-maldridge** [comment] 2017-07-03 05:46
This issue was resolved some time ago.

**Closed by the-maldridge** 2017-07-03 05:46 UTC
