### ISSUE TITLE
Package Request: 0ad

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#7681] opened 2017-09-16 05:47 UTC
...because it's everywhere but here. There wasn't even a package request which blew my mind. One of the best free software games out there.

**Comment by Hoshpak** [comment] 2017-09-16 07:19
duplicate of #2066 . I created a template for it some time ago but building it is a real pain (musl issues, nopie, bundled third-party libraries, cross-building issues) so the chances of it getting merged in it's current state would be close to zero.

**Comment by silvernode** [comment] 2017-09-17 17:22
That's sad to hear, but with that said I will close this issue on behalf of the existing issue post.

**Closed** 2017-09-17 17:23 UTC
Labels: Request
