### ISSUE TITLE
Audacity: build failure

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6692] opened 2017-06-12 16:03 UTC
Looks like a quoting problem with the flags that are passed to ./configure.  Then the errors propagated after are due to this initial fault. i.e. mkdir, pushd, which python

```
=== configuring in lib-src/lv2 (/builddir/audacity-Audacity-2.1.3/lib-src/lv2)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr'  '--sysconfdir=/etc' '--sbindir=/usr/bin' '--bindir=/usr/bin' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--localstatedir=/var' '--with-libsamplerate' '--host=x86_64-unknown-linux-gnu' '--build=x86_64-unknown-linux-gnu' 'build_alias=x86_64-unknown-linux-gnu' 'host_alias=x86_64-unknown-linux-gnu' 'CC=cc' 'CFLAGS=-specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   ' 'LDFLAGS=-specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -Wl,-z,relro -Wl,-z,now -Wl,--as
-needed    ' 'CPPFLAGS=   ' 'CPP=cpp' 'CXX=g++' 'CXXFLAGS=-specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   ' '--with-wx-config=/usr/bin/wx-config' '--enable-static=yes' '--enable-shared=no' '--disable-xmms-plugin' '--disable-doxygen-docs
' '--disable-thorough-tests' '--disable-programs' '--disable-programs' 'PORTAUDIO_CFLAGS=-I/builddir/audacity-Audacity-2.1.3/./lib-src/portaudio-v19/include' 'PORTAUDIO_LIBS=/builddir/audacity-Audacity-2.1.3/./lib-src/portaudio-v19/lib/libportaudio.la' --cache-file=/dev/null --srcdir=.
which: no python in (/builddir/.xbps-audacity/wrappers:/usr/bin:/usr/sbin:/usr/local/bin:/usr/loca/sbin)
which: no python2 in (/builddir/.xbps-audacity/wrappers:/usr/bin:/usr/sbin:/usr/local/bin:/usr/loca/sbin)
mkdir: unrecognized option '--prefix=.'
Try 'mkdir --help' for more information.
./configure: line 19: pushd: --prefix=.: invalid number pushd: usage: pushd [-n] [+N | -N | dir]
which: no python in (/builddir/.xbps-audacity/wrappers:/usr/bin:/usr/sbin:/usr/local/bin:/usr/loca/sbin)
which: no python2 in (/builddir/.xbps-audacity/wrappers:/usr/bin:/usr/sbin:/usr/local/bin:/usr/loca/sbin)

```

**Comment by ebfe** [comment] 2017-06-12 16:14
Can't reproduce. `./xbps-src pkg audacity` works fine on x86_64 glibc.

**Comment by Vaelatern** [comment] 2017-06-12 16:16
Also can't reproduce

**Comment by The-Fred** [comment] 2017-06-12 17:32
@ebfe my build is also x86_64 glibc but I am building without gcc4-compatible flag because a package I need won't work unless it uses _GLIBCXX_USE_CXX11_ABI=1. And I started with `./xbps-src bootstrap`


I found a file which is a symptom of the problem in: 

`/builddir/audacity-Audacity-2.1.3/lib-src/lv2/lv2`

`lrwxrwxrwx 1 r r    17 Jun 12 00:18 '*' -> '.././--prefix=./*'`

Do you see this file?

**Comment by Vaelatern** [comment] 2017-06-12 18:55
Please post a `diff -u` of your current template with the official template.

**Comment by Vaelatern** [comment] 2017-06-12 18:57
And these little details like "I changed stuff in `common/` or the template" actually really matter. You waste developer time by making us assume it's completely unchanged files that are the problem.

**Comment by The-Fred** [comment] 2017-06-12 19:26
No diffs as there are no template changes.  It takes time to file bugs, are you unappreciative of the time it takes for contributions?  Is your time more valuable? Please be clear on your response.

This issue may be related to 
https://github.com/voidlinux/void-packages/issues/6633

**Comment by ebfe** [comment] 2017-06-12 20:10
Where does `bin/sh` point to in your masterdir?

**Comment by The-Fred** [comment] 2017-06-12 22:15
The bin/sh is a link to bash and bash is an ELF 64-bit LSB shared object that's stripped (fwiw).

**Comment by cr6git** [comment] 2017-06-13 08:18
@The-Fred Try adding --without-lv2 in configure_args :wink:

**Comment by ebfe** [comment] 2017-06-13 15:40
@cr6git that won't fix the underlying problem. @The-Fred something is different/broken in your environment, without knowing what that is it's hard to help. `git diff` should show all changes you made (unless you committed them).

**Comment by The-Fred** [comment] 2017-06-13 17:29
@ebfe the only difference (I already said) was to change the ABI. gcc -v will show you the flags and which ABI your system uses.  Void is still way behind (and it's a known thing and will require a mass rebuild that takes weeks) at gcc4-compatible. But I need to build a package that needs the new ABI. 

But in another issue I reported there does seems to be a bug lurking within xbps-src that looks racey.  So possibly this problem is due to that.

#### https://github.com/voidlinux/void-packages/issues/6633

**Comment by ebfe** [comment] 2017-06-13 17:34
Good luck figuring it out.

**Comment by pullmoll** [comment] 2017-06-13 18:04
It looks like `/usr/bin/python` is missing or not executable in your environment. The `libs-src/lv2/configure` script does not check the results of `$(which python python2 | tail -n1)` when trying to execute e.g. `python waf ...`

Reading and understanding error messages is vital, if you intend to create new packages or if you modify the environment. You've got to find out why python can't be executed. Hint: `./xbps-src chroot` and try to run `python` to see what happens.

**Comment by pullmoll** [comment] 2017-06-13 18:08
P.S.: Do you `./xbps-src -N pkg …` when you try to build (-N being important here)? Otherwise you will pull in dependecies from the official server, which due to their `--with-default-libstdc++-abi=gcc4-compatible` build options may just not work in your environment.

**Comment by The-Fred** [comment] 2017-06-13 18:24
@ebfe not sure which "it" you refer to and relying on luck doesn't work too well with software usually. :/

@pullmoll Yes I pass -N, I am somewhat certain that trying to build Void with the new ABI yet mixing in packages using the old ABI would be a painful experience and I have doubts that I (or anyone) would get very far.  But even if I'm wrong I would not want to try because I don't need that setup.

Regarding python then, are you saying that Audacity is missing a dependency for python? That is what I am concluding based on your question.  Or is the dependency that's missing "waf"?

**Comment by pullmoll** [comment] 2017-06-13 18:29
No, python is already installed by a dependency, at least for native builds and in my local environment. Cross builds won't work anyway because of wxWidgets-devel not being cross compilable.

I don't think adding python to hostmakedepends will solve your issue. We have no waf package, so it has to be some waf script internal to audacity that is to be interpreted here.

**Comment by The-Fred** [comment] 2017-06-13 18:50
@pullmoll I trust what you say when you conclude python is not found by Audacity build. But my environment isn't custom except that one setting for the ABI.  So if for some reason python's not found/there then audacity should have provided python? 

Should this command work to completion?
`./xbps-src -N -C pkg audacity`

Or do I (or anyone) need to run some other command first?  I have been doing that and presuming that command would be enough and xbps-src would get what it needs to pkg audacity.  

Should I run `./xbps-src -N -C pkg python` then the audacity command?

I haven't removed or cleaned or done anything other than run `./xbps-src -N -C pkg pkgnamegoeshere `  commands.  So did something remove python???  Am I proceeding incorrectly? I have started with pkg gcc and now I am up to ~790 pkgs in the index. But it required lots of restarts along the way. Maybe some failure (see the issues I've logged) put my env into an unexpected state??

**Comment by pullmoll** [comment] 2017-06-14 00:29
Why the fuck don't you just try what I suggested, but insist on guessing other pecularities?
If I give you advice, why don't you just follow it?

This is the last time I'll answer to this non-issue for the current build environment.

If python isn't installed when audacity is about to be build, we have a dependency problem elsewhere. Why don't you simply try what I suggest, if I take the time to even look at your issue? It's not that I get paid for looking at other people's problems. So once more and as simple as it could be stated:

After `./xbps-src -N pkg audacity` fails run, execute `./xbps-src chroot` and enter `python` to see any error message, because there's not anything else I could imagine except `python` failing to execute. Period.

And if this test passes, we may be able to look for other causes why the configure script's command line `$(which python python2 | tail -n1)` command is failing. But please stop guessing before looking! You can _always_ find the cause for an error, if you take look at log files or simply take the easiest path to verify your environment is sane. And if you are not able to look into log files or find a cause, at least please listen to advices and follow them.

Don't guess, just enter the environment and _test_ what you expect to be there.
Guessing does not even help the most experienced devs in many cases.
Don't try to be smarter than the ones who're trying to help you.
You'll fail.

Cheers
pullmoll

**Comment by The-Fred** [comment] 2017-06-14 01:03
@pullmoll  funny response!  You already determined python wasn't there so why go looking for an answer we already have. The correct question to answer is "Why python wasn't there?" 

Do you or anyone else not know xbps-src well enough to say what cases in a regular xbps-src x86_64 glibc environment where that can happen? 

As for guessing I definitely don't know what that line of thought is about. I've not done any guessing and just reported what I encountered.

I got work to do so obviously I didn't keep the environment around. I moved on.  But let me know if Void doesn't want issues raised, I'll definitely not bother if it's not something wanted/needed.

My big surprise is to find that xbps-src really won't run unattended with any largish number of packages to be built. It requires much care and feeding.

**Comment by pullmoll** [comment] 2017-06-14 01:29
Sad. Your repsonse does not include an answer to my requests. Instead you are scattering hard-to-guess facts about your build environment every now an then.

You're trying to be smarter than me, you're trying to delude me, while it seems you ain't that much smarter - or you would have figured the cause.

No, I don't know "xbps-src well enough" to tell anything. Seemingly you think you are. Huh?

I don't think "Void doesn't want issues raised", while my best guess is that other contributors are trying harder to solve their issues before raising an issue. But that's of course just my point of view on this entirely voluntary project and its contributors.

You seem to be trying to be negative, if someone asked me to give a prejudice opinion about you. But then: that's just me, not any majority. I for one would have entered `python` in a chroot and reported its output. This may be due to my experience that following advice sometimes helps.

How did @ebfe put it? Good luck figuring it out!
(where "it" may be something irrational)

**Comment by The-Fred** [comment] 2017-06-14 02:13
Yes I answered you, this problem was encountered and I raised this issue and forged ahead. You must be thinking that I froze the environment at that point. Can't afford to do that with limited resources. 

I am glad you pointed out that we are all voluntary. Don't forget the "we".

**Comment by Vaelatern** [comment] 2017-06-14 02:21
Until you are willing to share what you changed to get these unreproducible results, I will close this issue. One remark: Do make sure your user is in the `xbuilder` group.

**Closed by Vaelatern** 2017-06-14 02:21 UTC

**Comment by pullmoll** [comment] 2017-06-14 02:34
Aw.. k.

**Comment by Duncaen** [comment] 2017-06-14 02:49
You clearly broke your environment by randomly rebuilding packages with the new abi.
You have to increase revisions to rebuild packages and you should have done a new bootstrap from source.
Don't share just small parts of the build logs, the python package should be already installed.
Is your python package broken? Does it contains the python binary?

**Comment by cr6git** [comment] 2017-06-14 13:05
I can compile Audacity 2.1.3 without problem, see my [log](https://paste2.org/vjXvFmhf)...
