### ISSUE TITLE
Bug in common/build-style/python-module.sh breaks python-setuptools build.

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6633] opened 2017-06-08 20:59 UTC
Bug here:

https://github.com/voidlinux/void-packages/blob/master/common/build-style/python-module.sh#L24

```
=> python-setuptools-33.1.1_1: verifying checksum for distfile 'setuptools-33.1.1.zip'... OK.
=> python-setuptools-33.1.1_1: running do-extract hook: 00-distfiles ...
=> python-setuptools-33.1.1_1: extracting distfile(s), please wait...
=> python-setuptools-33.1.1_1: running post-extract hook: 00-patches ...
=> python-setuptools-33.1.1_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> python-setuptools-33.1.1_1: running pre-configure hook: 01-override-config ...
=> python-setuptools-33.1.1_1: running pre-configure hook: 02-script-wrapper ...
=> python-setuptools-33.1.1_1: running pre-build hook: 02-script-wrapper ...
=> python-setuptools-33.1.1_1: running do_build ...
/void-packages/common/build-style/python-module.sh: line 24: python2.7: command not found
=> ERROR: python-setuptools-33.1.1_1: failed to run do_build() at line 24.

```

**Comment by Vaelatern** [comment] 2017-06-08 21:02
Perhaps you meant to include `python` in your `hostmakedepends`. If there was actually a bug there, a lot more would be broken.

**Comment by Vaelatern** [comment] 2017-06-08 21:04
As it turns out, it's our template, and it does have `python-devel` in `hostmakedepends`. All I can think of is you need to clean and try again.

**Comment by The-Fred** [comment] 2017-06-09 21:04
Ran into this one also, no idea if it's related for certain but it does look similar in that they both might be a race condition.  i.e. something was expected to be done already but the program got to the point of need before the need was fulfilled.

I was using `./xbps-src -C pkg`

```
=> libGL-17.1.1_1: verifying checksum for distfile 'mesa-17.1.1.tar.xz'... OK.
=> libGL-17.1.1_1: running do-extract hook: 00-distfiles ...
=> libGL-17.1.1_1: extracting distfile(s), please wait...
=> libGL-17.1.1_1: running post-extract hook: 00-patches ...
=> libGL-17.1.1_1: patching: musl-endian.patch.
=> libGL-17.1.1_1: patching: musl.patch.
=> libGL-17.1.1_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> libGL-17.1.1_1: running pre-configure hook: 01-override-config ...
=> libGL-17.1.1_1: running pre-configure hook: 02-script-wrapper ...
=> libGL-17.1.1_1: running pre_configure ...
/void-packages/srcpkgs/libGL/template: line 87: libtoolize: command not found
=> ERROR: libGL-17.1.1_1: failed to run pre_configure() at line 87.
```

**Comment by asergi** [comment] 2017-06-13 21:23
Can't reproduce.

**Comment by Vaelatern** [comment] 2017-06-14 02:18
Until you are willing to share what you changed, I'm closing this issue.

**Closed by Vaelatern** 2017-06-14 02:18 UTC
