### ISSUE TITLE
GDM broken

### ISSUE THREAD

**Issue by maxice8** [voidlinux/void-packages#8765] opened 2017-11-01 05:47 UTC
### System

* xuname:  $ sudo xuname
Void 4.13.9_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
* architecture:  x86_64
* libc:  glibc
* package: gdm-3.26.1 

### Expected behavior

GDM starting and showing a display for login.

### Actual behavior

Flashing black screen indefinitively

### Steps to reproduce the behavior

1. Install gdm `xbps-install -S gdm`
2. enable it as a service ( `ln -s /etc/sv/gdm /var/service` ) or just run it (`gdm`)

**Comment by maxice8** [comment] 2017-11-01 05:51
[/var/log/gdm/greeter.log](https://p.iotek.org/e8f
) ( when using default options )

/var/log/gdm/greeter.log ( when WaylandEnable=True )

```
Unable to register display with display manager
```

**Comment by maxice8** [comment] 2017-11-01 05:53
Could be related ( [arch bug report](https://bugs.archlinux.org/task/56190?project=1&cat%5B0%5D=2&string=gdm) )

**Comment by maxice8** [comment] 2017-11-02 06:48
New error in new version

```
Unable to run session
```

This is also after running `find /tmp/gdm-runtime-dir -exec sh -c 'chown gdm:root {}' \;` so it would stop crying about permission in those directories, the original owners were rtkit:bluetooth

**Comment by Vaelatern** [comment] 2017-11-02 18:55
xorg installed?

**Comment by maxice8** [comment] 2017-11-02 18:57
On Thu, Nov 02, 2017 at 06:55:36PM +0000, Toyam Cox wrote:
> xorg installed?
> 

Yes

**Comment by Gottox** [comment] 2017-11-09 07:02
Is elogind running?

Can you enable Debug mode in custom.conf?

**Comment by maxice8** [comment] 2017-11-09 08:10
On Thu, Nov 09, 2017 at 07:02:17AM +0000, Enno Boland wrote:
> Is elogind running?
> 

Will check this shortly, doing my daily bumps

**Comment by abenson** [comment] 2018-01-24 22:46
Does gdm require cgmanager? I'm having the same problem with gdm right now (flickers when attempting to start). Xorg works fine (verified with startx). 

ConsoleKit is running, but cgmanager fails to start.

~~~
cgmanager: Error mounting unified: No such file or directory

cgmanager: failed to collect cgroup subsystems
~~~

I'm still trying to figure out this issue, hoping it might be the cause.

**Comment by Johnnynator** [comment] 2018-01-25 06:18
Nope, gdm runs without cgmanager fine on my machine

**Comment by Gottox** [comment] 2018-01-25 06:55
gdm and gnome in general are using elogind instead of consolekit. Closing the issue for now. please comment if the issue persists for anyone.

**Closed by Gottox** 2018-01-25 06:55 UTC

**Comment by abenson** [comment] 2018-01-25 12:55
Okay, then maybe the gdm template isn't pulling in something that's required. I ended up removing gdm and going with lightdm, until gdm is fixed.
