### ISSUE TITLE
youtube-viewer-3.3.1_1 on Raspberry Pi B+ SSLeay.c: loadable library and perl binaries are mismatched (got handshake key 0x9300080, needed 0x9000080)

### ISSUE THREAD

**Issue by ProinsiasC** [voidlinux/void-packages#8184] opened 2017-10-15 16:13 UTC
Fresh install on Raspberry Pi B+

youtube-viewer-3.3.1_1  starts up fine just calling youtube-viewer but the result of a search or starting with a query 'youtube-viewer string' results in:

> SSLeay.c: loadable library and perl binaries are mismatched (got handshake key 0x9300080, needed 0x9000080)

architecture: armv6l
build-date: 2017-10-13 10:38 CEST
filename-sha256: fa412819ae0346dfe5d5c47e1758d8408d13f7923abc6e6b4681be253c095ea7
filename-size: 63KB
homepage: https://github.com/trizen/youtube-viewer
install-date: 2017-10-15 15:13 UTC
installed_size: 453KB
license: Artistic-2.0
maintainer: Duncaen <duncaen@voidlinux.eu>
metafile-sha256: aca79b6cc60fc030f11886860a5b0ebaae7a53210182f40c301be24d633bad73
pkgver: youtube-viewer-3.3.1_1
repository: https://repo.voidlinux.eu/current
short_desc: Command-line client to search and stream from YouTube
source-revisions: youtube-viewer:6ca7e5987a
state: installed

**Comment by cr6git** [comment] 2017-10-16 14:45
Is there a problem with `perl-Module-Build` template ? 
````
# Template file for 'perl-Module-Build'
pkgname=perl-Module-Build
version=0.4224
revision=1
noarch=yes
wrksrc="${pkgname/perl-/}-${version}"
build_style=perl-module
hostmakedepends="perl"
makedepends="${hostmakedepends}"
depends="${makedepends}"
short_desc="Module::Build - Build and install Perl modules"
maintainer="Leah Neukirchen <leah@vuxu.org>"
homepage="http://search.cpan.org/dist/Module-Build/"
license="Artistic, GPL-1"
distfiles="${CPAN_SITE}/Module/${pkgname/perl-/}-${version}.tar.gz"
checksum=a6ca15d78244a7b50fdbf27f85c85f4035aa799ce7dd018a0d98b358ef7bc782

pre_configure() {
	unset XBPS_CROSS_BASE
}
````
I don't know exactly what `pre_configure()` is doing here ?

**Comment by wesbarnett** [comment] 2017-12-22 17:45
ddclient-3.8.3_1 gives the exact same error. Does `perl-Net-SSLeay` need to be rebuilt?

**Comment by pullmoll** [comment] 2017-12-22 19:05
It's more the packages that need a rebuild AFAICT. I revbumped both of them.

**Comment by Duncaen** [comment] 2017-12-22 19:18
I don't think `youtube-viewer` or `ddclient` needs to be rebuilt, but `perl-Net-SSLeay` which links libperl.
Maybe we can find a solution to make binary perl modules are depend on the libperl version instead of `>=`, this happens every time perl is updated.

**Comment by pullmoll** [comment] 2017-12-23 11:36
@Duncaen 
> Maybe we can find a solution to make binary perl modules are depend on the libperl version instead of >=, this happens every time perl is updated.

Well, I don't know how the library interacts with the modules, but it seems this is the cause. Depending on the exact version should list all dependent modules once you change the line libperl.so.5.26 in common/shlibs?

**Comment by newbluemoon** [comment] 2018-10-24 13:09
Should have been resolved by https://github.com/void-linux/void-packages/pull/2358.

**Comment by pullmoll** [comment] 2018-10-31 17:57
Closing under the assumption it was fixed.

**Closed by pullmoll** 2018-10-31 17:57 UTC
