### ISSUE TITLE
w3m can't load images

### ISSUE THREAD

**Issue by TheDoctorsLife** [voidlinux/void-packages#4245] opened 2016-05-28 22:49 UTC
Pulling this upstream from
https://github.com/dylanaraps/neofetch/issues/256
w3m can't load pictures.
![terminator](https://i.imgur.com/5UGUo2h.png)
![xfce4-terminal](https://camo.githubusercontent.com/494ff3f871e6b1099f60633574860d86a64a578e/687474703a2f2f692e696d6775722e636f6d2f7a6750706635482e706e67)

**Comment by Vaelatern** [comment] 2016-05-29 05:07
Can you tell if this might be related to uncompface not being present at build time (or packaged for void at all?)

**Comment by TheDoctorsLife** [comment] 2016-05-29 05:19
ATM I cannot, however I can build it locally and try rebuilding w3m-img with it.

**Comment by chneukirchen** [comment] 2016-05-29 14:30
I had an issue due to the line `imgdisplay w3mimgdisplay-` in my `.w3m/config`.

After removing the final `-`, it worked again.

(No idea what you are doing in that screenshot, `w3m image ...` never worked.)

**Comment by chneukirchen** [comment] 2016-05-29 14:34
`neofetch` works fine here, tho:

![2016-05-29-163359_480x312_scrot](https://cloud.githubusercontent.com/assets/139/15634053/42830f44-25bb-11e6-8250-a056afb59c18.png)

**Comment by TheDoctorsLife** [comment] 2016-05-29 14:45
`.w3m/config` doesn't exist on my system, after making it and putting that line into the config it still didn't work.

**Comment by Vaelatern** [comment] 2016-05-29 15:18
Working just fine when I load the images from this issue.
I recommend the following: `w3m ~/Pictures/Doctors.png`

**Comment by TheDoctorsLife** [comment] 2016-05-29 15:22
Is it supposed to just open imagemagick, rather then rendering it in the terminal?

**Comment by ebfe** [comment] 2016-06-03 12:17
The problem isn't loading  it's rendering. w3m-img assumes 24 bit depth (or whatever DefaultDepth() return). I guess the people for which this doesn't work are using terminals with 32-bit depth. Debian has some patches that might address this http://anonscm.debian.org/cgit/collab-maint/w3m.git/log/w3mimg/x11/x11_w3mimg.c

**Comment by artsi0m** [comment] 2016-08-14 18:36
![links](https://cloud.githubusercontent.com/assets/18009816/17651073/2464c8ac-6267-11e6-80a0-162633b77193.png)

**Comment by ebfe** [comment] 2016-12-09 03:07
Should be fixed since e211ce202f6b5ea9dce9498982fae55afe14b59a.

**Closed by ebfe** 2016-12-09 03:07 UTC
Labels: Bug
