### ISSUE TITLE
Package request: pandoc

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#885] opened 2015-01-18 06:26 UTC
Can you pleas add pandoc from: https://github.com/jgm/pandoc

Description 

Pandoc is a [Haskell] library for converting from one markup format to
another, and a command-line tool that uses this library. It can read
[markdown] and (subsets of) [Textile], [reStructuredText], [HTML],
[LaTeX], [MediaWiki markup], [TWiki markup], [Haddock markup], [OPML],
[Emacs Org-mode], [DocBook], [txt2tags], [EPUB] and [Word docx]; and
it can write plain text, [markdown], [reStructuredText], [XHTML],
[HTML 5], [LaTeX] (including [beamer] slide shows), [ConTeXt], [RTF],
[OPML], [DocBook], [OpenDocument], [ODT], [Word docx], [GNU Texinfo],
[MediaWiki markup], [DokuWiki markup], [Haddock markup], [EPUB] (v2 or v3),
[FictionBook2], [Textile], [groff man] pages, [Emacs Org-Mode], [AsciiDoc],
[InDesign ICML], and [Slidy], [Slideous], [DZSlides], [reveal.js] or
[S5] HTML slide shows. It can also produce [PDF] output on systems where
LaTeX is installed.

**Comment by xtraeme** [comment] 2015-01-18 08:21
Duplicate of #220

**Closed by xtraeme** 2015-01-18 08:21 UTC
