### ISSUE TITLE
spectrwm problems with Void musl

### ISSUE THREAD

**Issue by spaceille** [voidlinux/void-packages#12820] opened 2018-03-23 03:11 UTC
### System

* xuname:  
  *Void 4.15.12_1 x86_64-musl GenuineIntel uptodate rF*
* package:  
  *spectrwm V3.0.2 Build: 3.0.2*

### Expected behavior
WM starts itself and programmes declared in the config file with `autorun`

### Actual behavior
WM doesn't start at all (only on a system with musl; work perfectly with glibc)
### Steps to reproduce the behavior
add any programme the config file in the autorun section; log out; log back in
[spectrwm.conf.txt](https://github.com/voidlinux/void-packages/files/1840031/spectrwm.conf.txt)

**Comment by Vaelatern** [comment] 2018-03-23 05:18
Logs?
"Doesn't start at all" is, surprisingly, ambiguous.

**Comment by spaceille** [comment] 2018-03-23 12:26
Please tell me which logs are you interested in? Here is Xorg log, but it seams very useless to me for the purpose of debugging the WM. I couldn't find any mention of logs for spectrwm either on my FS or in the documentation. 
[Xorg.0.log.old.txt](https://github.com/voidlinux/void-packages/files/1841440/Xorg.0.log.old.txt)
.

**Comment by mvf** [comment] 2018-03-23 12:39
Don't worry about the logs @spaceille, I'm pretty sure I know what the problem is. Fix is in the works.

**Closed** 2018-03-24 16:27 UTC
