### ISSUE TITLE
ERROR: ncurses-6.0_2: failed to run do-fetch_00-distfiles() at line 17.

### ISSUE THREAD

**Issue by jmfgdev** [voidlinux/void-packages#6788] opened 2017-06-19 13:52 UTC
=> ERROR: ncurses-6.0_2: failed to run do-fetch_00-distfiles() at line 17.

I get this error when trying to run `xbps-src bootstrap`
I apologize if this is user error but due to the fact that the error report gives me a specific line I figured this could be an actual issue.

**Comment by jmfgdev** [comment] 2017-06-19 14:27
It seems that folder are not made automatically, and creating folders is soliving the problem bit by bit, I create a folder related to an error, the program then manages to run a bit further till it reaches another error of a nonexistent directory.

I now reach this error:
```
gcc-6.3.0_3: broken, unresolvable shlib `libgcc_s.so.1'
gcc-6.3.0_3: broken, unresolvable shlib `libstdc++.so.6'
Transaction aborted due to unresolved shlibs.
[DEBUG] [pkgdb] released ok.
=> ERROR: ncurses-6.0_2: cannot continue!
```

**Comment by Vaelatern** [comment] 2017-06-19 16:24
Sadly, automatic bootstrap is presently broken. Thank you for your investigation!

**Comment by The-Fred** [comment] 2017-06-21 19:08
JimmyBot try this url for pcre https://ftp.pcre.org/pub/pcre/pcre-8.40.tar.gz 

Va el tren I haven't found the issue logged for the bootstrap breakage, can you post the link?

**Comment by the-maldridge** [comment] 2017-06-24 01:24
@The-Fred it almost certainly isn't logged.  Its so infrequent that we bootstrap or try to bootstrap another architecture that it often has issues.  If you'd like to help, you can try and bootstrap x86_64 on a beefy machine, make sure you set XBPS_MAKEJOBS to a reasonable value.  That will probably need to run overnight, and then when it crashes, make a new issue with the complete build log in it.

**Comment by The-Fred** [comment] 2017-06-26 17:02
@the-maldridge I have run bootstrap recently and filed issues. I needed a newer ABI than gcc4-compatible. Don't have logs and have moved along.

For a rolling release some things are not rolling.  Yeah I know resources are limited but a call to arms might shake out some resources. Even if only to test out bootstrap. There was a forum member offering up some hardware/bandwidth. Maybe not huge iron but what does that matter if it's dedicated to just bootstrap. I suppose trust issues could also be an important factor. (they usually always are)

**Comment by the-maldridge** [comment] 2017-06-26 19:35
@The-Fred please take your rant somewhere that isn't an issue for a library.

@jmfgdev I cannot reproduce this issue so I'm going to go ahead and close this ticket.  If you still have issues with ncurses, please reopen this issue.

**Closed by the-maldridge** 2017-06-26 19:35 UTC

**Comment by The-Fred** [comment] 2017-06-26 20:48
@the-maldridge you brought up the bootstrap and suggested running bootstrap.  Va el tren seems to have done so. But I don't see the logs or an issue created for the bootstrap breakage. Please take it up with va el tren.

**Comment by jmfgdev** [comment] 2017-06-26 20:50
His name isn't "va el tren" it's Vaelatern
