### ISSUE TITLE
Package request: calibre

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1262] opened 2015-04-03 00:28 UTC
Calibre is an ebook reader/collector

http://calibre-ebook.com/

**Comment by dominikh** [comment] 2015-04-03 00:48
Duplicate of #248

**Closed by dominikh** 2015-04-03 00:48 UTC

**Comment by thypon** [comment] 2015-04-03 01:22
Could we rename the other with standard syntax?

**Comment by dominikh** [comment] 2015-04-03 01:25
> Something went wrong with that request. Please try again

Apparently not. Maybe someone else will have more luck.

**Comment by thypon** [comment] 2015-06-17 14:37
Me had more luck :-P
