### ISSUE TITLE
qemu: OpenGL not supported

### ISSUE THREAD

**Issue by ackalker** [voidlinux/void-packages#4988] opened 2016-10-17 18:32 UTC
On Void Linux x86_64 (glibc), when I boot a VM configured according to: http://blog.wikichoon.com/2016/05/spice-openglvirgl-acceleration-on.html in `virt-manager`, I get the following error:

```
Error starting domain: unsupported configuration: This QEMU doesn't support spice OpenGL

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 88, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 124, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 83, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1404, in startup
    self._backend.create()
  File "/usr/lib/python2.7/site-packages/libvirt.py", line 1035, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: unsupported configuration: This QEMU doesn't support spice OpenGL
```

A quick test using `qemu-system-x86_64` directly, using SDL, gives:

``` sh
$ qemu-system-x86_64 -display sdl,gl=on
SDL1 display code has no opengl support.
Please recompile qemu with SDL2, using
./configure --enable-sdl --with-sdlabi=2.0
qemu-system-x86_64: OpenGL is not supported by the display
```

It appears that there is no OpenGL support with either SPICE or SDL.
Please rebuild `qemu` package so it works with OpenGL acceleration.
Thanks in advance.

**Comment by ackalker** [comment] 2016-10-17 18:39
Ah, I see that the configure options to make this work are controlled by `build_options` in the `qemu` package template. What is the reason that `sdl2` is excluded from `build_options_default`? Why is `virgl` included in both `build_options` and `build_options_default`?

**Comment by ackalker** [comment] 2016-10-17 22:05
I've built `qemu` with working OpenGL in SDL by setting `sdl2` option, but I haven't been able to get it to work with SPICE.

Something very weird is going on:
```
$ qemu-system-x86_64 -help | sed -ne '/^-spice/,/^-/p'
-spice [port=port][,tls-port=secured-port][,x509-dir=<dir>]
[..snip..]
       [,gl=[on|off]]
   enable spice
   at least one of {port, tls-port} is mandatory
```
This appears to indicate that support is available, however:
```sh
$ qemu-system-x86_64 -device virtio-vga,virgl=on -spice gl=on,unix,addr=/run/user/1000/spice.sock
qemu-system-x86_64: -spice gl=on,unix,addr=/run/user/1000/spice.sock: Invalid parameter 'gl'
```
I'm at a loss here.

**Comment by ackalker** [comment] 2016-10-17 22:49
I think I've found the issue: [this line](https://github.com/voidlinux/void-packages/blob/2115e199dcb0200a4fdbddc7cb456a0a9857a8b7/srcpkgs/qemu/template#L20) in the template tests the `spice` option even before it gets appended to `build_options_default` by [this line](https://github.com/voidlinux/void-packages/blob/2115e199dcb0200a4fdbddc7cb456a0a9857a8b7/srcpkgs/qemu/template#L33)

**Comment by ackalker** [comment] 2016-10-18 13:54
Resolved: in `qemu` source, `include/ui/spice-display.h` lines 28-29:
```c
# if SPICE_SERVER_VERSION >= 0x000d01 /* release 0.13.1 */
#  define HAVE_SPICE_GL 1
[..snip..]
```
`spice` package in Void Linux isn't new enough:
```sh
$ xbps-query -p pkgver spice
spice-0.12.7_2
```
It would have been nice if `qemu`'s `configure` had complained about the version requirement right at the start.

**Comment by Gottox** [comment] 2016-10-31 08:31
Spice-0.13 is a developer release. We're updating spice once the stable is out. In case we forgot to rebuild qemu then, please ping me in this PR, @ackalker.

**Comment by Gottox** [comment] 2016-10-31 09:44
Closing for now. please reopen on release.

**Comment by vanyasem** [comment] 2017-11-20 09:27
I guess it's time to re-open this issue. Installed latest stable Spice (0.14) and latest QEMU from git. Yet was not able to make OpenGL working

**Comment by anchev** [comment] 2017-11-22 21:58
I followed the instructions in [Spice User Manual](https://www.spice-space.org/spice-user-manual.html#_gl_acceleration_virgl). The hardware is Asus P8Z77-V, i7-3770, GTX 680. Using virt-manager-1.4.1-4.1.noarch on openSUSE Leap 42.3:

1. Changed video to virtio and turned on 3D acceleration.
![image](https://user-images.githubusercontent.com/10694926/33150439-1d09a490-cfdc-11e7-9ab7-4d7202225ec2.png)

2. Set display spice section accordingly trying both rendernode options as shown in virt-manager screenshot below:
![image](https://user-images.githubusercontent.com/10694926/33150354-bd2bd67e-cfdb-11e7-9146-1a6b99026da5.png)

As you can see there is some strange yellow icon hovering which shows a tooltip informing that `Graphics listen type does not support spice GL` (any idea why?).

The sections in the xml file for the guest look like:
```
<graphics type='spice' autoport='yes' listen='127.0.0.1' keymap=''>
  <listen type='address' address='127.0.0.1'/>
  <gl enable='yes' rendernode=''/> # when choosing "Auto" from the dropdown; rendernode='/dev/dri/renderD128 when choosing "0000:01:00:0 NVIDIA Corporation GK104 [GeForce GTX 680] (render)" in virt-manager
</graphics>
<video>
  <model type='virtio' heads='1' primary='yes'>
    <acceleration accel3d='yes'/>
  </model>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
</video>
```
Similar to the OP pressing the "Play" button to power on the VM shows a window:

```
Error starting domain: unsupported configuration: This QEMU doesn't support spice OpenGL

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 88, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 124, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 83, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1489, in startup
    self._backend.create()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1062, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: unsupported configuration: This QEMU doesn't support spice OpenGL
```
I also tried adding manually in the `<features>` section of the xml file:

```
<kvm>
      <hidden state='on'/>
</kvm>
```
as per the advise given in [this comment](https://www.youtube.com/watch?v=d3HL9x0CEtY&lc=z120sdwrovnjxtmon04ced3azsnwvhdhtd0.1510930553679877&feature=em-comments) but that didn't improve anything.

I hope someone can help with that. I have been fighting it for more than 2 years, asking in various forums and other sites. The replies I usually get is "that is not an easy question" or "it is quite new technology" etc. However I see that people have been able to do VGA passthrough:

https://www.youtube.com/watch?v=37D2bRsthfI
https://www.youtube.com/watch?v=d3HL9x0CEtY

**Comment by Gottox** [comment] 2017-11-23 09:20
@anchev To clarify: You're running a voidlinux guest on an opensuse host?

**Comment by Gottox** [comment] 2017-11-23 09:21
How did you guys test opengl was not working?

**Comment by anchev** [comment] 2017-11-23 09:23
@Gottox no. The guest is Windows 7 x64.

I explained the exact steps how I test. If there is anything else that needs to be tested - please explain the steps, so I can provide further feedback.

**Comment by Gottox** [comment] 2017-11-23 10:08
> I followed the instructions in Spice User Manual. The hardware is Asus P8Z77-V, i7-3770, GTX 680. Using virt-manager-1.4.1-4.1.noarch on openSUSE Leap 42.3

So Windows is the guest, VoidLinux runs libvirt and you're using virtmanager to access the void system? Please explain your setup.

**Comment by vanyasem** [comment] 2017-11-23 10:12
The guest is Windows 7 x64 for me as well

**Comment by xtraeme** [comment] 2017-11-23 10:16
This is completely unrelated to voidlinux... the host is opensuse.

**Comment by anchev** [comment] 2017-11-23 10:23
> So Windows is the guest, VoidLinux runs libvirt and you're using virtmanager to access the void system? Please explain your setup.

openSUSE Leap 42.3 installed on bare metal (host)
Windows 7 x64 is the guest.
Using virt-manager.
Never heard of VoidLinux (before seeing this thread).

I reported here because while searching the web for solutions to my problem I found this issue which shows the exact same error which I am experiencing.

**Comment by Gottox** [comment] 2017-11-23 10:26
@anchev This would've been a very useful information.

**Comment by Gottox** [comment] 2017-11-23 10:28
@vanyasem Can you explain your setup and give steps to reproduce?

**Comment by anchev** [comment] 2017-11-23 10:29
@Gottox sorry for not being clear from the beginning. If there is anything else I should test please let me know. I really need to get 3D acceleration in guest.

**Comment by Gottox** [comment] 2017-11-23 10:31
This issue is specific to voidlinux as we're just introducing GL support. I don't think we can help with third party distributions.

**Closed** 2018-03-27 08:01 UTC
Labels: Bug
