### ISSUE TITLE
libreoffice: build times out on the builders

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#9159] opened 2017-11-13 22:18 UTC
https://build.voidlinux.eu/builders/x86_64-musl_builder/builds/6050/steps/shell_3/logs/stdio
```
[...]
[build MOD] libreoffice
[build BIN] top level modules: libreoffice
[build ALL] top level modules: build-non-l10n-only build-l10n-only
[build SLC] sw
[build SLC] libreoffice

command timed out: 14400 seconds without output running ['make'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=20314.285378
```

[build SLC] is apparently the "slowcheck" target which runs the "slow unit tests". Since this doesn't reproduce locally it's hard to figure out what's actually happens on the builder and there is no apparent way to disable the "slow" checks. Any idea @pullmoll?

**Comment by ebfe** [comment] 2017-11-14 06:47
The hanging process is cppunittester and it's stuck in a futex syscall.

**Comment by ebfe** [comment] 2017-11-14 09:03
`CXXFLAGS+=" -DDISABLE_CVE_TESTS=1"` which is already set for i686 seems to fix this (hard to say for sure since this triggers rarely locally).

**Comment by ebfe** [comment] 2017-11-14 09:21
Nope, DISABLE_CVE_TEST was bogus...

**Comment by emacsomancer** [comment] 2017-11-14 18:30
Is this connected to (new version of) libreoffice on glibc correctly requiring libpoppler.so.72, but the musl version still requiring libpoppler.so.71?

**Comment by ebfe** [comment] 2017-11-14 18:31
Yes, the builder is stuck, thus the musl version hasn't been updated.

**Comment by pullmoll** [comment] 2017-11-15 09:03
Sorry for the delay. I could try to update to 5.4.3.2 which I had built locally.

**Comment by pullmoll** [comment] 2017-11-15 18:56
After disabling the slowchecks target in the makefile I could build for x86_64-musl here.
I hope the builders can finish now.

**Comment by pullmoll** [comment] 2017-11-15 21:16
So x86_64-musl builder segfaults when trying to check sccomp. I tend to believe that one or several of the dependencies need to be rebuilt with gcc-7.2.0.

Or perhaps something is otherwise broken on the x86_64-musl builders. I've seen it building packages which then were not registered, because they already were in the repo. Why does this happen?

**Comment by ebfe** [comment] 2017-11-15 21:27
> So x86_64-musl builder segfaults when trying to check sccomp. I tend to believe that one or several of the dependencies need to be rebuilt with gcc-7.2.0.

Wouldn't that mean the glibc builder should have the same problem?

> Or perhaps something is otherwise broken on the x86_64-musl builders.
> I've seen it building packages which then were not registered, because
> they already were in the repo. Why does this happen?

There is currently something wrong with the setup on the musl builders.
xbps-checkvers doesn't use the correct or an empty repodata to determine
what needs to be build.

**Comment by pullmoll** [comment] 2017-11-15 21:42
> > So x86_64-musl builder segfaults when trying to check sccomp. I tend to believe that one or several of the dependencies need to be rebuilt with gcc-7.2.0.

> Wouldn't that mean the glibc builder should have the same problem?

In theory, yes. It's difficult to guess the underlying problem because I can't reproduce it locally.

**Comment by pullmoll** [comment] 2017-11-16 10:28
Fixed by not running checks at all for x86_64-musl.

**Closed by pullmoll** 2017-11-16 10:28 UTC

**Comment by ebfe** [comment] 2017-11-16 11:39
Thanks. fwiw using a musl libc with bigstack enabled also didn't help.

**Comment by pullmoll** [comment] 2017-11-16 11:40
Alpine disables the checks as well for 5.4.2.2 so it seems they already tried and failed.
