### ISSUE TITLE
xbps-src crossbuilding for armv6hf-musl broken on x86_64 (perhaps cross-*-libc packages should not be noarch)

### ISSUE THREAD

**Issue by CMB** [voidlinux/void-packages#2738] opened 2015-10-13 05:55 UTC
When I try to cross-build anything for armv6hf-musl with xbps-src
on my x86_64 machine, it always fails, usually at the assembler stage.
$masterdir/usr/arm-linux-musleabihf/usr/bin/as
is called as the assembler, but that file
is provided by cross-arm-linux-musleabihf-libc, a noarch package.
$masterdir/usr/arm-linux-musleabihf/usr/bin/as
is in fact a 32-bit ELF executable for 80386.

This really seems to affect all the cross-*-libc packages.  I just happened
to have the bad luck to notice it, since cross-arm-linux-musleabihf-libc
came from i686 and I'm on x86_64.

**Comment by xtraeme** [comment] 2015-10-16 10:04
I believe your masterdir is broken.

Try

```
$ ./xbps-src zap && ./xbps-src binary-bootstrap
```

Please provide log files if you can still reproduce this.

Thanks

**Comment by CMB** [comment] 2015-10-17 07:48
Yes, this was my first thought as well.
I've zapped and binary-bootstrapped several times.
I've even rm -rf'ed the whole masterdir, just to insure that I had
killed it with fire.  No luck.
Here's the log of me trying to build sic.
I picked this at random just for demo purposes.
http://the-brannons.com/armv6hf-musl-build.log

I also made a patch that "fixes" the cross-* packages, but maybe it's
not perfect.  See the crosslibcs branch of github.com/CMB/void-packages

Thanks.

**Comment by pullmoll** [comment] 2015-10-17 17:24
The error is you do `./xbps-src binary-bootstrap` and later `./xbps-src -a armv6hf-musl pkg sic`.
You have to zap everything (or use a different `-m masterdir-musl`) and do `./xbps-src binary-bootstrap x86_64-musl` first.

**Comment by CMB** [comment] 2015-10-17 18:36
Wow, that works.  But the question is, why can I crossbuild for other
-musl architectures with my original masterdir, but specifically not
armv6hf-musl?  I've used that same masterdir to crossbuild for
armv7hf-musl, x86_64-musl, and perhaps a couple of others, with no
problems.

http://the-brannons.com/morelogs.txt

**Comment by pullmoll** [comment] 2015-10-17 22:23
I have no idea actually. I always followed the manual which somewhere says that you need the same libc type IIRC. I think you can't compile the `cross-*-linux-*` packages across the masterdir's glibc / musl type either.

**Comment by pullmoll** [comment] 2015-10-18 01:00
I think the issue is solved, so I'm closing this...

**Closed by pullmoll** 2015-10-18 01:00 UTC
