### ISSUE TITLE
Tracking issue: gcc 7

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#6321] opened 2017-05-03 12:46 UTC
Fallout from Fedora:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7OS7EDKLZDY27C6777O6HE2QMF7YU3X7/

**Comment by q66** [comment] 2017-05-04 14:44
That thread is pretty old, looks like majority of those problems should not be present in the actual release version of GCC7... though there could still be a lot of errors due to projects' use of `-Werror`, which will probably need to be patched away (and ideally fixed upstream, because using `-Werror` in standard builds is just asking for problems anyway)

**Comment by pullmoll** [comment] 2017-05-04 16:55
We should perhaps consider creating a `chroot-glibc` package and use that for building gcc. The regular `glibc` package would then later be built with the new compiler and not be `bootstrap=yes`.

I think so because LFS has a two stage build process where the glibc built with a foreign (old) compiler is just an intermediate. The binary output of a glibc built with `gcc-6.3.0` and `gcc-7.1.0` will most probably be different.

This may apply to binutils and some more packages as well.

**Comment by chneukirchen** [comment] 2017-05-04 16:58
Do we really need that? Currently, we can just bootstrap somehow, and then build chroot twice...

**Comment by pullmoll** [comment] 2017-05-04 17:13
This is how we did it last time, yes. But that's not documented anywhere.
Perhaps describing that a rebuild of the chroot is advised suffices everyone.

**Comment by pullmoll** [comment] 2017-05-08 10:25
Fixes for gcc-7.1.0
- [x] diffutils needed a patch for __builtin_add_overflow()

**Comment by pullmoll** [comment] 2017-05-08 11:08
Some interesting possible buffer overrun errors in the xbps package. Thinking about how to fix these.
```
make[1]: Entering directory '/builddir/xbps-0.51/include'
sed -e "s|@@VERSION@@|0.51|g" xbps.h.in > xbps.h
make[1]: Leaving directory '/builddir/xbps-0.51/include'
make[1]: Entering directory '/builddir/xbps-0.51/lib'
 [GEN]		fetch/httperr.h
 [CC]		portableproplib/rb.o
 [CC]		portableproplib/prop_array.o
 [CC]		portableproplib/prop_dictionary.o
 [CC]		portableproplib/prop_ingest.o
 [GEN]		fetch/ftperr.h
 [CC]		portableproplib/prop_bool.o
 [CC]		portableproplib/prop_stack.o
 [CC]		portableproplib/prop_string.o
 [CC]		portableproplib/prop_object.o
 [CC]		portableproplib/prop_array_util.o
 [CC]		portableproplib/prop_dictionary_util.o
 [CC]		portableproplib/prop_number.o
 [CC]		portableproplib/prop_zlib.o
 [CC]		portableproplib/prop_data.o
 [CC]		package_configure.o
 [CC]		package_config_files.o
 [CC]		package_orphans.o
 [CC]		package_remove.o
 [CC]		package_find_obsoletes.o
 [CC]		package_state.o
 [CC]		package_unpack.o
 [CC]		package_script.o
 [CC]		package_register.o
 [CC]		verifysig.o
 [CC]		package_msg.o
 [CC]		pkgdb_conversion.o
 [CC]		transaction_shlibs.o
 [CC]		transaction_commit.o
 [CC]		transaction_package_replace.o
 [CC]		transaction_dictionary.o
 [CC]		transaction_ops.o
 [CC]		transaction_store.o
 [CC]		transaction_revdeps.o
 [CC]		transaction_conflicts.o
 [CC]		pubkey2fp.o
 [CC]		package_fulldeptree.o
 [CC]		download.o
 [CC]		initend.o
 [CC]		pkgdb.o
 [CC]		plist.o
 [CC]		plist_find.o
 [CC]		plist_match.o
 [CC]		archive.o
 [CC]		plist_remove.o
 [CC]		plist_fetch.o
 [CC]		util.o
 [CC]		util_hash.o
 [CC]		repo.o
 [CC]		repo_pkgdeps.o
 [CC]		repo_sync.o
 [CC]		rpool.o
 [CC]		cb_util.o
 [CC]		proplib_wrapper.o
 [CC]		package_alternatives.o
 [CC]		external/dewey.o
 [CC]		external/fexec.o
 [CC]		external/mkpath.o
initend.c: In function 'xbps_init':
initend.c:418:10: error: '%s' directive output may be truncated writing 11 bytes into a region of size between 1 and 512 [-Werror=format-truncation=]
       "%s%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "",
          ^~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 12 and 523 bytes into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:424:7: error: '__builtin___snprintf_chk' output may be truncated before the last format character [-Werror=format-truncation=]
       "%s/%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "", buf);
       ^~~~~~~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 2 or more bytes (assuming 513) into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:429:9: error: '%s' directive output may be truncated writing 17 bytes into a region of size between 1 and 512 [-Werror=format-truncation=]
      "%s%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "",
         ^~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 18 and 529 bytes into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:450:11: error: '%s' directive output may be truncated writing 14 bytes into a region of size between 0 and 511 [-Werror=format-truncation=]
       "%s/%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "",
           ^~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 16 and 527 bytes into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:456:7: error: '__builtin___snprintf_chk' output may be truncated before the last format character [-Werror=format-truncation=]
       "%s/%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "", buf);
       ^~~~~~~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 2 or more bytes (assuming 513) into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:462:11: error: '%s' directive output may be truncated writing 12 bytes into a region of size between 0 and 511 [-Werror=format-truncation=]
       "%s/%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "",
           ^~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 14 and 525 bytes into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initend.c:468:7: error: '__builtin___snprintf_chk' output may be truncated before the last format character [-Werror=format-truncation=]
       "%s/%s", strcmp(xhp->rootdir, "/") ? xhp->rootdir : "", buf);
       ^~~~~~~
In file included from /usr/i686-pc-linux-gnu/usr/include/stdio.h:939:0,
                 from initend.c:29:
/usr/i686-pc-linux-gnu/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 2 or more bytes (assuming 513) into a destination of size 512
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:71: initend.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/xbps-0.51/lib'
make: *** [Makefile:15: all] Error 1
=> ERROR: xbps-0.51_18: failed to run do_build() at line 14.
```

**Comment by pullmoll** [comment] 2017-05-09 17:37
First live images (base system) are being uploaded [here](http://repo.voidlinux.de/live/).

**Comment by q66** [comment] 2017-05-09 18:15
nice, when do you see this getting into the main repo?

**Comment by pullmoll** [comment] 2017-05-09 23:20
As soon as we got all main package's build errors solved and find a window to actually rebuild all c++ pkgs from scratch. This will be a time of outages and failures to update the entire system AFAICT.

**Comment by pullmoll** [comment] 2017-05-30 17:34
Similar to `qt5` also `firefox-esr fails` to build for `i686*`:
```
creating ./config.status
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
ValueError: semaphore or lock released too many times

^CProcess PoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap

    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
```

There is some bug lurking in 32bit Python-2.7 semaphore creation or handling, becoming visible only with newer GCCs, which is not yet identified and fixed.

**Comment by ebfe** [comment] 2017-06-24 23:26
Looking at the python patch i'm wondering if this really is the cause, or rather some (rarely triggered) race condition in the calling code.

**Comment by pullmoll** [comment] 2017-07-11 05:34
@ebfe It's most probably a race condition and it is almost certainly related to 32 bit vs. 64 bit initialization of variables or structures. I haven't found patches addressing this problem yet. Building qt5 still fails for i686*.

**Comment by pullmoll** [comment] 2017-07-15 15:42
FWIW I tried to build `python` (2.7) with `gcc-7.1.1` for `i686` now defining `CFLAGS="-DHAVE_BROKEN_SEM_GETVALUE=1"` and this gets me rid of the abovementioned error when trying to build `firefox-esr`.

I think we could incorporate this flag in `srcpkgs/python/template` at least for `i686` like:
```
case "$XBPS_TARGET_MACHINE" in
        i686*)  CFLAGS="-DHAVE_BROKEN_SEM_GETVALUE=1" ;;
esac
```
and remove `srcpkgs/python/patches/fix-i686-semaphore_lock.patch` altogether.

Any objections?

**Comment by cr6git** [comment] 2017-07-24 08:03
@pullmoll I can see your brand-new ISOs dated 17 July 2017, great work!

**Comment by chneukirchen** [comment] 2017-08-01 20:48
Bump. When shall we merge this?

**Comment by pullmoll** [comment] 2017-08-02 04:48
We should (must) first build world with it before merging, because the gcc4 compatibility is gone and all packages (at least the ones using C++) must be updated at once. We should thus switch repositories together with the merge, or we would cause a lot of trouble.

Furthermore I couldn't get cross-i686-musl to build right, which is no major show stopper.

**Comment by chneukirchen** [comment] 2017-08-15 18:04
gcc 7.2 has been released now.

**Comment by pullmoll** [comment] 2017-08-16 07:40
I am [trying now](https://github.com/pullmoll/void-packages-gcc7) with gcc-7.2.0.
We can remove the glibc-2.26 and the SOURCE_DATE_EPOCH patches.
The latter is now implemented in gcc itself.

**Comment by pullmoll** [comment] 2017-08-16 14:32
I think we need to talk about how an upgrade can be done:
1. Build gcc without `--with-default-libstdcxx-abi=gcc4-compatible`
    Every libstdc++ related package needs to be revbumped and rebuilt.
2. Build gcc with `--with-default-libstdcxx-abi=gcc4-compatible`
    Updating gcc and the cross compilers may be sufficient.

The choice 1. is of course desirable, while it requires a lot of computing and man power.
I don't think we can update one pkg after another, but need to do a repository update or switch once all libstdc++ related pkgs are rebuilt. This parallel rebuilding will receive interferences from regular pkg updates and their version or revision bumps. I also don't know, if we actually have the computing power to do this somewhere?

**Comment by chneukirchen** [comment] 2017-08-16 14:37
I think #1 is possible by ordering the package bumps properly, but it will take quite some time.

#2 we can do now, and rather independently.

**Comment by pullmoll** [comment] 2017-08-16 14:46
Choice 2. would also leave us some time to fix glibc-2.26 induced breakage, like llvm or more specific compiler-rt, which would need a rebuild with 1.
I just don't know, if there are downsides to keeping the libstdcxx-abi gcc4 compatible.

**Comment by chneukirchen** [comment] 2017-08-16 14:59
There are certain C++11 programs that don't compile on gcc4 abi, but I didn't see them in the wild yet.
(So far our packages worked of course. ;))

**Comment by pullmoll** [comment] 2017-08-16 15:04
The links tell there should be no influence of -std=c++11 e.g. to this flag or vice-versa.
I agree we should go 2. and make it a rather smooth transition.
I also believe we do not even need to bootstrap, but can just update the compilers this time.

**Comment by chneukirchen** [comment] 2017-08-16 16:36
Yes, should do it.

**Comment by pullmoll** [comment] 2017-08-16 16:43
libgfortran.so.3 changed to libgfortran.so.4 which requires some revbumps:
arpack-ng, blas, lapack, libmitlm, octave, openblas, python{,3}-scipy

**Comment by pullmoll** [comment] 2017-08-16 18:29
For cross-i686-linux-musl the error seen before is still there:
```
configure: error: Pthreads are required to build libatomic
make[1]: *** [Makefile:16174: configure-target-libatomic] Error 1
config.status: executing libtool commands
make[1]: Leaving directory '/builddir/cross-i686-linux-musl-0.24/gcc-build'
make: *** [Makefile:897: all] Error 2
```
I'll retry with `--disable-libatomic` as in `cross-i686-pc-linux-gnu`

**Comment by chneukirchen** [comment] 2017-08-17 10:30
This is only i686 musl, yes?

**Comment by pullmoll** [comment] 2017-08-17 12:50
Yes. All other cross compilers built fine here.

**Comment by q66** [comment] 2017-11-03 13:32
time to close this i guess?

**Closed** 2018-03-01 19:59 UTC
Labels: large
